config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :answers
    end
  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
Class AnswersController << ApplicationController

def create
  @question = Question.find(params[:questions_id])
  @answer = @question.answer.build(answer_params)
  @answer.user = current_user
  @answer.save
  redirect_to questions_url
end

def destroy
  @question = Question.find(params[:questions_id])
  @answer = @question.answer.find(params[:id]).destroy
  redirect_to questions_url
end

private

def answer_params
  params.required(:answer).permit(:content)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  # layout '_default'
  # protect_from_forgery with: :exception
  # prepend_before_action :authenticate_user!, raise: false
end

app/controllers/home_controller.rb
class HomeController < BaseController
  # load_and_authorize_resource
  #
  # before_action  only: [:new, :create]
  def index
    if user_signed_in?
      redirect_to questions_path
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  end

  def login
  end

  def welcome
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  end
end

app/helpers/aplication_helper.rb
module AplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_default.html.erb
<%= render layout: 'layouts/application' do %>
  <% if user_signed_in? %>
    welcome <%= current_user.email %>
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to 'Sign in', new_user_session_path %>
  <% end %>
  <%= yield %>
  <div id="wrapper">
    <!-- Navigation -->
    <%#= render 'layouts/navigation' %>

    <!-- Page wraper -->
    <div id="page-wrapper" class="gray-bg">

      <!-- Page wrapper -->
      <%#= render 'layouts/topnavbar' %>

      <div class="wrapper wrapper-content animated fadeInRight">
        <% flash.each do |type, msg| %>
          <div class="<%= flash_class(type) %>">
            <%= msg %>
          </div>
        <% end %>

        <%= yield %>
      </div>

    </div>

  </div>

  <%#= render 'layouts/footer' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestRuby</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if user_signed_in? %>
  welcome <%= current_user.email %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %>
<%= yield %>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.content %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>